import type { PipelineConfig } from "../types";

const DEBRIEF_ROOT =
  ".planning/initiatives/vision-alignment-2026-04/debrief";

export const visionAlignment202604Config: PipelineConfig = {
  id: "vision-alignment-2026-04",
  label: "Vision Alignment Initiative 2026-04",
  outputRoot: `${DEBRIEF_ROOT}/artifacts/transcript-nlp`,
  anchorTerms: [
    "vision alignment",
    "vision-alignment-2026-04",
    "phase 4",
    "round 1.5",
    "boundary-contract-memo",
    "research-principles",
    "review gate",
    "formal audit",
    "roadmap",
    "d1",
    "d2",
    "d3",
    "d4",
    "d5",
    "codex",
    "claude",
  ],
  stageDefinitions: [
    {
      id: "trigger-and-setup",
      label: "Trigger And Setup",
      start: "2026-04-08T00:00:00.000Z",
      end: "2026-04-10T23:59:59.999Z",
    },
    {
      id: "wave-execution-and-audit",
      label: "Wave Execution And Audit",
      start: "2026-04-11T00:00:00.000Z",
      end: "2026-04-11T23:59:59.999Z",
    },
    {
      id: "debrief",
      label: "Debrief",
      start: "2026-04-16T00:00:00.000Z",
      end: "2026-04-16T23:59:59.999Z",
    },
  ],
  sources: [
    {
      id: "claude-project",
      kind: "claude-project",
      provider: "claude",
      basePath:
        "~/.claude/projects/-home-rookslog-workspace-projects-f1-modeling",
      startDate: "2026-04-08",
      endDate: "2026-04-16",
      includeTopLevelSessions: true,
      includeSubagentSessions: true,
    },
    {
      id: "codex-sessions",
      kind: "codex-sessions",
      provider: "codex",
      basePath: "~/.codex/sessions",
      startDate: "2026-04-08",
      endDate: "2026-04-16",
      workspacePath: ".",
    },
    {
      id: "initiative-logs",
      kind: "plain-log",
      provider: "initiative-log",
      defaultStageId: "trigger-and-setup",
      filePaths: [
        ".planning/initiatives/vision-alignment-2026-04/logs/wave-1A.log",
        ".planning/initiatives/vision-alignment-2026-04/logs/wave-1B.log",
        ".planning/initiatives/vision-alignment-2026-04/logs/wave-1C.log",
      ],
    },
  ],
  lanes: [
    {
      id: "claude-chat",
      label: "Claude Chat Extract",
      outputPath: `${DEBRIEF_ROOT}/extracts/claude-chat-extract.md`,
      providerAllowlist: ["claude"],
      familyIds: [
        "positive_collaboration",
        "frustration_pushback",
        "clarification_ambiguity",
        "authorization_delegation",
        "audit_protocol",
        "review_gate_restructure",
        "model_role_shift",
      ],
      requiredFamilies: [
        "positive_collaboration",
        "frustration_pushback",
        "authorization_delegation",
        "audit_protocol",
      ],
      requiredProviders: ["claude"],
      contextBefore: 2,
      contextAfter: 3,
      maxMoments: 12,
      softTokenCap: 100_000,
      preferredTokenTarget: 80_000,
      preferredOutputTokenTarget: 1_500,
    },
    {
      id: "codex-chat",
      label: "Codex Chat Extract",
      outputPath: `${DEBRIEF_ROOT}/extracts/codex-chat-extract.md`,
      providerAllowlist: ["codex"],
      familyIds: [
        "positive_collaboration",
        "frustration_pushback",
        "clarification_ambiguity",
        "authorization_delegation",
        "audit_protocol",
        "review_gate_restructure",
        "model_role_shift",
        "agent_usage",
      ],
      requiredFamilies: [
        "positive_collaboration",
        "frustration_pushback",
        "authorization_delegation",
        "agent_usage",
      ],
      requiredProviders: ["codex"],
      contextBefore: 2,
      contextAfter: 3,
      maxMoments: 12,
      softTokenCap: 100_000,
      preferredTokenTarget: 80_000,
      preferredOutputTokenTarget: 1_500,
    },
    {
      id: "cross-model-and-agent-usage",
      label: "Cross-Model And Agent Usage Extract",
      outputPath: `${DEBRIEF_ROOT}/extracts/cross-model-and-agent-usage-extract.md`,
      providerAllowlist: ["claude", "codex", "initiative-log"],
      familyIds: [
        "positive_collaboration",
        "frustration_pushback",
        "authorization_delegation",
        "audit_protocol",
        "review_gate_restructure",
        "model_role_shift",
        "agent_usage",
      ],
      requiredFamilies: [
        "positive_collaboration",
        "audit_protocol",
        "model_role_shift",
        "agent_usage",
      ],
      requiredProviders: ["claude", "codex", "initiative-log"],
      contextBefore: 1,
      contextAfter: 2,
      maxMoments: 10,
      softTokenCap: 100_000,
      preferredTokenTarget: 80_000,
      preferredOutputTokenTarget: 1_500,
    },
  ],
};
