import type { QueryFamily } from "./types";

export const QUERY_FAMILIES: QueryFamily[] = [
  {
    id: "positive_collaboration",
    label: "Positive Collaboration",
    description: "Moments where the interaction clearly improved the work or aligned on a valuable correction.",
    importance: "Preserves what went well rather than only collecting failure.",
    patterns: [
      /\bgood catch\b/i,
      /\byou'?re right\b/i,
      /\blet'?s do that\b/i,
      /\bthat makes sense\b/i,
      /\bimportant\b/i,
      /\bexactly\b/i,
      /\bhelpful\b/i,
    ],
    actorAllowlist: ["user", "assistant"],
    baseScore: 4,
  },
  {
    id: "frustration_pushback",
    label: "Frustration Or Pushback",
    description: "Turns where the user or assistant signals dissatisfaction, challenge, or a correction with heat.",
    importance: "Surfaces process friction, quality concerns, and failure-recovery moments.",
    patterns: [
      /\bannoy/i,
      /\bfrustrat/i,
      /\bsloppy\b/i,
      /\badhoc\b/i,
      /\btoo narrow\b/i,
      /\blaziness\b/i,
      /\bdon'?t like\b/i,
      /\bwe cannot afford\b/i,
      /\bshouldn'?t\b/i,
      /\bhold on\b/i,
    ],
    actorAllowlist: ["user", "assistant"],
    baseScore: 5,
  },
  {
    id: "clarification_ambiguity",
    label: "Clarification Or Ambiguity",
    description: "Turns asking for clarification, more specificity, or signaling ambiguity.",
    importance: "Captures where intent or implementation meaning was unstable.",
    patterns: [
      /\bunclear\b/i,
      /\bclarif/i,
      /\bconfus/i,
      /\bambigu/i,
      /\bmore specific\b/i,
      /\bwhat about\b/i,
      /\bhow are we\b/i,
      /\bwhat do you mean\b/i,
    ],
    actorAllowlist: ["user", "assistant"],
    baseScore: 3,
  },
  {
    id: "authorization_delegation",
    label: "Authorization Or Delegation",
    description: "Turns discussing launches, authorization boundaries, agents, or delegation assumptions.",
    importance: "Important for review-gate discipline and agent-usage analysis.",
    patterns: [
      /\bauthoriz/i,
      /\blaunch\b/i,
      /\bdelegate\b/i,
      /\bsubagent\b/i,
      /\bagent\b/i,
      /\bsublane\b/i,
      /\bwhile we wait\b/i,
      /\bxhigh\b/i,
      /\bone at a time\b/i,
      /\bproceed\b/i,
    ],
    actorAllowlist: ["user", "assistant", "system"],
    baseScore: 4,
  },
  {
    id: "audit_protocol",
    label: "Audit Or Protocol",
    description: "Turns that discuss audits, review gates, protocols, handoffs, or decision-record mechanics.",
    importance: "Captures auditability and procedural integrity.",
    patterns: [
      /\baudit\b/i,
      /\bprotocol\b/i,
      /\breview gate\b/i,
      /\bdecision record\b/i,
      /\bformal audit\b/i,
      /\bpost-hoc\b/i,
      /\bhandoff\b/i,
    ],
    baseScore: 5,
  },
  {
    id: "review_gate_restructure",
    label: "Review Gate Or Restructure",
    description: "Turns referencing plan restructuring, wrong-sized framing, Round 1.5, or the boundary memo.",
    importance: "Captures major process turns where the initiative changed shape.",
    patterns: [
      /\bwrong-sized\b/i,
      /\brestructure/i,
      /\bboundary(?:\/|-| )contract(?:\/|-| )memo\b/i,
      /\bround 1\.5\b/i,
      /\bsplit r5\b/i,
      /\bphase 4\b/i,
    ],
    baseScore: 4,
  },
  {
    id: "model_role_shift",
    label: "Model Role Shift",
    description: "Turns discussing Codex/Claude roles, fallback behavior, or cross-model review.",
    importance: "Needed for cross-model and role-fit analysis.",
    patterns: [
      /\bcodex\b/i,
      /\bclaude\b/i,
      /\bcross-model\b/i,
      /\bcross-vendor\b/i,
      /\bfallback\b/i,
      /\borchestrator\b/i,
    ],
    baseScore: 4,
  },
  {
    id: "agent_usage",
    label: "Agent Usage",
    description: "Turns discussing worker/subagent use, parallelism, or reasoning-effort choices.",
    importance: "Needed for agent-quality analysis and delegation review.",
    patterns: [
      /\bsubagent\b/i,
      /\bagent\b/i,
      /\bworker\b/i,
      /\bparallel\b/i,
      /\breasoning_effort\b/i,
      /\bxhigh\b/i,
      /\bhigh reasoning\b/i,
      /\bnickname\b/i,
    ],
    baseScore: 4,
  },
];

export const QUERY_FAMILY_MAP = new Map(
  QUERY_FAMILIES.map((family) => [family.id, family]),
);
